# s3-bucket-stack.yaml
apiVersion: cloudformation.aws.crossplane.io/v1alpha1
kind: CloudFormationStack
metadata:
  name: s3-bucket-stack
  namespace: crossplane-system
spec:
  forProvider:
    region: us-west-2
    templateBody: |
      AWSTemplateFormatVersion: '2010-09-09'
      Resources:
        MyBucket:
          Type: AWS::S3::Bucket
          Properties:
            BucketName: my-crossplane-bucket
  providerConfigRef:
    name: aws-provider